name: Continuous Integration

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ "2.6", "2.7", "3.0" ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        run: bundle exec rspec --profile 10 --format progress

      - name: Lint
        run: bundle exec rubocop --config .rubocop.yml --parallel --display-cop-names

  release:
    name: Release application
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Build and push to RubyGems
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release

      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Gem ${{ github.event.repository.name }} ${{ env.VERSION }} was released
